test_guru/config/routes.rb
Rails.application.routes.draw do
  resources :tests do
    resources :questions, except: [:index], shallow: true do
      resources :answers, shallow: true
    end

    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
      get :result, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

test_guru/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :right, -> { where(correct: true) }

  validates :body, presence: true
  validate :answers_quantity, on: :create

  def answers_quantity
    errors.add(:question_id, 'more than 4 answers') if
      question.answers.count >= 4
  end
end

test_guru/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

test_guru/app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :nullify

  validates :title, presence: true, uniqueness: true
end

test_guru/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

test_guru/app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User'
  has_many :questions, dependent: :destroy
  has_many :test_passages
  has_many :users, through: :test_passages, dependent: :destroy

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }

  scope :by_category, ->(category_name) { joins(:category).where(categories: { title: category_name }).order(title: :desc) }

  validates :title, presence: true, uniqueness: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.category_by_title_desc(category_name)
    by_category(category_name).pluck(:title)
  end
end

test_guru/app/models/test_author.rb
class TestAuthor < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

test_guru/app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_first_question, on: :create
  before_save :next_question, on: :update

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_questions?(answer_ids)
      self.correct_question += 1
    end
    save!
  end

  def correct_answers
    current_question.answers.right
  end

  def question_number
    self.test.questions.index(current_question) + 1
  end

  private

  def set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_questions?(answer_ids)
    begin
      correct_answers.ids.sort == answer_ids.map(&:to_i).sort
    rescue => exception
      retry
    end
    
  end

  def next_question
    self.current_question = test.questions.order(:id).where('id >?', current_question.id).first
  end


end

test_guru/app/models/user.rb
class User < ApplicationRecord
  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :author_tests, class_name: 'Test', foreign_key: 'author_id'

  validates :email, presence: true, uniqueness: true

  def test_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test: test)
  end
end

test_guru/app/models/user_test.rb
class UserTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

test_guru/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[show edit update destroy]
  before_action :find_question, only: %i[new create]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = Answer.new(answer_params)
    if @answer.save
      redirect_to @answer
    else
      render :new
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    if @answer.update(answer_params)
      redirect_to @answer
    else
      render :new
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    redirect_to @answer.question
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = Answer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end
end

test_guru/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

test_guru/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_test, only: %i[index create new]
  before_action :find_question, only: %i[destroy update edit show]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_record_not_found

  def show; end

  def new
    @question = @test.questions.new
  end

  def edit; end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def destroy
    @question.destroy
    redirect_to @question.test
  end

  def update
    if @question.update(question_params)
      redirect_to tests_path
    else
      render :edit
    end
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_record_not_found
    head :not_found
    render plain: 'Record not found!'
  end
end

test_guru/app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :set_test_passage, only: %i[show update result]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

test_guru/app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :find_test, except: %i[index new create]
  before_action :find_user, only: :start

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def index
    @tests = Test.all
  end

  def new
    @categories = Category.all
    @author = User.all
    @test = Test.new
  end

  def edit; end

  def create
    @test = Test.new(test_params)

    if @test.save
      redirect_to @test
    else
      render :new
    end
  end

  def show
    @questions = @test.questions
  end

  def update
    if @test.update(test_params)
      redirect_to @test
    else
      render :edit
    end
  end

  def start
    @user.tests.push(@test)
    redirect_to @user.test_passage(@test)
  end

  def destroy
    @test.destroy
    redirect_to tests_path
  end

  private

  def test_params
    params.require(:test).permit(:title, :level, :category_id, :author_id)
  end

  def find_test
    @test = Test.find(params[:id])
  end

  def find_user
    @user = User.first
  end

  def rescue_with_test_not_found
    render plain: 'Test was not found!'
  end
end

test_guru/app/helpers/answers_helper.rb
module AnswersHelper
end

test_guru/app/helpers/application_helper.rb
module ApplicationHelper
  def today
    Date.current.year
  end

  def github_url(author, repo = '')
    text = repo == '' ? author : repo
    link_to text, "https://github.com/#{author}/#{repo}", target: '_blank'
  end

  def thinknetica_link
    link_to 'Учебный проект в онлайн-школе Thinknetica', 'http://thinknetica.com', target: '_blank'
  end
end

test_guru/app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Question"
    else
      "Edit #{question.body} Question"
    end
  end
end

test_guru/app/helpers/test_passages_helper.rb
module TestPassagesHelper

  def result_test
      question_size = @test_passage.test.questions.size.to_f
      correct_size =  @test_passage.correct_question.to_f
      result = ((correct_size / question_size))*100
  end


end

test_guru/app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || 'hero'
  end
end

test_guru/app/views/answers/_answer.html.erb
<li>
  <%= answer.body %>
  <%= link_to 'Show', answer_path(answer) %>
  <%= link_to 'Edit', edit_answer_path(answer) %>
  <%= link_to 'Delete',
                  answer_path(answer),
                  method: :delete,
                  data: { confirm: 'Are your sure?' } %>

  <br>
</li>

test_guru/app/views/answers/_form.html.erb
<%= form_with model: [@question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

<p>
  <%= form.label :body %><br>
  <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
</p>

<p>
  <%= form.label :correct %>:
  <%= form.check_box :correct,id: :answer_correct %>
</p>

<p><%= form.submit %></p>
<% end %>

test_guru/app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %>
<%= link_to 'Back', @answer.question %>

test_guru/app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', @answer.question %>

test_guru/app/views/answers/show.html.erb
<h1>Question</h1>
<%= @answer.question.body %>
<p>
  <strong>Answer:</strong>
  <%= @answer.body %>
</p>
<p>
  <strong>Correct:</strong>
  <%= @answer.correct %>
</p>



<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', @answer.question %>

test_guru/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>

    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

test_guru/app/views/questions/_form.html.erb
<%= form_with model: [@test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>

  <p>
    <%= form.label :body %>
    <%= form.text_field :body, id: :question_body %>
  </p>

  <p><%= form.submit %></p>
<% end %>

test_guru/app/views/questions/_question.html.erb
<tr>
  <br>
  <td><%= question.id %></td>
  <td><%= question.body %></td>
  <td><%= link_to 'Show', question_path(question) %></td>
  <td><%= link_to 'Edit', edit_question_path(question) %></td>
  <td><%= link_to 'Delete',
                  question_path(question),
                  method: :delete,
                  data: { confirm: 'Are your sure?' } %>
  </td>
</tr>

test_guru/app/views/questions/edit.html.erb
<h1><%= question_header @question %></h1>


<%= render 'form' %>

<p>
<%= link_to 'Back', tests_path %>
</p>

test_guru/app/views/questions/new.html.erb
<h1><%= question_header @question %></h1>

<%= @question.body %>

<%= render 'form' %>

<p>
<%= link_to 'Back', test_path(@test.id) %>
</p>

test_guru/app/views/questions/show.html.erb
<p>
  <strong>ID:</strong>
  <%= @question.id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @question.body %>
</p>

<h2>Answers</h2>

<%= link_to 'New answer', new_question_answer_path(@question) %>

<p>
  <%= render @question.answers %>
</p>

<%= link_to 'Back', tests_path %>

<%= link_to 'Edit', edit_question_path(@question) %>

test_guru/app/views/shared/_errors.html.erb
<% if resource.errors.present? %>
  <div>
    <h2><%= pluralize(resource.errors.count, 'error') %></h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

test_guru/app/views/shared/_footer.html.erb
<p>Author github: Smolin Arthur "<%= github_url('drujok')%>"</p>
  <p>Project github: <%= github_url('drujok','Rails')%></p>
<p>About: Проект TestGuru это замечательная образовательная платформа<br>
  для создания и прохождения тестов по различным темам.<br>
Разработка проекта ведется на Ruby on Rails.</p>
<p><%= thinknetica_link %></p>

<%= today %>

test_guru/app/views/shared/_nav.html.erb
<p>
  <%= link_to 'New test', new_test_path %>
</p>

test_guru/app/views/test_passages/_testresult.html.erb
<% if result_test >= 85 %>
  <b style="color:green"><%= result_test.round(2) %>%
  <br>  "Test passed!"
  </b>
<% else %>
  <b style="color:red"><%= result_test.round(2) %>%
  <br>  "Test failed!"
  </b>
<% end %>

test_guru/app/views/test_passages/result.html.erb
<h1>The Ruby Test was Completed!</h1>

<b>Quantity of questions:</b>
<%= @test_passage.test.questions.size %>
<br>
<b>Right Answers:</b>
<%= @test_passage.correct_question %>
<br>
<b>Test result:</b>
<%= render 'testresult' %>

<p>
<%= link_to 'Back', tests_path %>
</p>

test_guru/app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.title %> Test</h1>

<p>Кол-во вопросов в тесте:</p>
<b>
 <%= @test_passage.test.questions.size %>
</b>
<br>
<p>Текущий вопрос:</p>
<b>
 <%= @test_passage.question_number %>
</b>
<p>Осталось вопросов:</p>
<b>
  <%= @test_passage.test.questions.size - @test_passage.question_number.to_i  %>
</b>


<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body,include_hidden: false do |b| %>
   <p>
     <%= b.check_box id: "answer_ids_#{b.object.id}" %>
     <%= b.label %>
   </p>
  <% end %>

  <%= form.submit 'Next' %>
<% end %>